/**
 * Property Inspection Module Exports
 *
 * This module provides comprehensive property inspection management functionality
 * including types, services, queries, and state management.
 */

// Export all query hooks
export {
  inspectionKeys,
  useAvailableInspectors,
  useBulkUpdateInspections,
  useCancelInspection,
  useChecklistTemplates,
  useCompleteInspection,
  useConfirmTenantAttendance,
  useCreateInspection,
  useCreateInspectionTemplate,
  useCreateRecurringInspection,
  useDeleteInspection,
  useDeleteInspectionAttachment,
  useDeleteInspectionTemplate,
  useDeleteRecurringInspection,
  useDuplicateInspection,
  useExportInspections,
  useGenerateInspectionReport,
  useGenerateNextInspection,
  useInspection,
  useInspectionCalendarEvents,
  useInspectionStats,
  useInspections,
  useInspectionsByProperty,
  useInspectionTemplates,
  useInspectorAvailability,
  useInvalidateInspections,
  useOverdueInspections,
  usePrefetchInspection,
  usePropertyInspectionHistory,
  useRecurringInspections,
  useRescheduleInspection,
  useSendInspectionNotification,
  useSendInspectionReminder,
  useUpcomingInspections,
  useUpdateInspection,
  useUpdateInspectionChecklist,
  useUpdateInspectionTemplate,
  useUpdateRecurringInspection,
  useUploadInspectionAttachment,
  useValidateInspectionConflicts,
} from "./inspection.queries";
// Export all service functions
export {
  bulkUpdateInspections,
  cancelInspection,
  completeInspection,
  confirmTenantAttendance,
  createInspection,
  createInspectionTemplate,
  createRecurringInspection,
  deleteInspection,
  deleteInspectionAttachment,
  deleteInspectionTemplate,
  deleteRecurringInspection,
  downloadInspectionReport,
  duplicateInspection,
  exportInspections,
  generateInspectionReport,
  generateNextInspection,
  getAvailableInspectors,
  getChecklistTemplates,
  getInspection,
  getInspectionCalendarEvents,
  getInspectionStats,
  getInspections,
  getInspectionsByProperty,
  getInspectionTemplates,
  getInspectorAvailability,
  getOverdueInspections,
  getPropertyInspectionHistory,
  getRecurringInspections,
  getUpcomingInspections,
  rescheduleInspection,
  sendInspectionNotification,
  sendInspectionReminder,
  updateInspection,
  updateInspectionChecklist,
  updateInspectionTemplate,
  updateRecurringInspection,
  uploadInspectionAttachment,
  validateInspectionConflicts,
} from "./inspection.service";
// Export store and selectors
export {
  useCurrentInspection,
  useHasSelectedInspections,
  useInspectionFilters,
  useInspectionForm,
  useInspectionLoading,
  useInspectionModal,
  useInspectionModals,
  useInspectionQueryParams,
  useInspectionStore,
  useInspectionViewMode,
  // useActiveFiltersCount,
  useInspectionViewPreferences,
  useSelectedInspections,
  useSelectedInspectionsCount,
  // useBulkActionLoading,
  // useActiveProperty,
} from "./inspection.store";
// Export all types
export type {
  ApiResponse,
  BulkInspectionOperation,
  CompleteInspectionInput,
  CreateInspectionInput,
  InspectionAttachment,
  InspectionCalendarEvent,
  InspectionChecklistItem,
  InspectionFilters,
  InspectionListResponse,
  InspectionNotificationSettings,
  InspectionQueryParams,
  InspectionRecurrence,
  InspectionReport,
  InspectionReportResponse,
  InspectionResponse,
  InspectionStats,
  InspectionStatsResponse,
  InspectionTemplate,
  InspectionTemplatesResponse,
  InspectorAvailability,
  Pagination,
  PropertyInspection,
  RecurringInspection,
  RescheduleInspectionInput,
  UpdateInspectionInput,
} from "./inspection.type";
// Export enums
export { InspectionStatus, InspectionType } from "./inspection.type";
