title = "Kaa API Gitleaks Config"

[[rules]]
id = "generic-api-key"
description = "Generic API Key"
regex = '''(?i)((api|app|aws|azure|github|gitlab|google|slack|stripe|twilio)_?(key|token|secret)|access_?(key|token|secret))[ ]*[:=][ ]*['"][0-9a-zA-Z]{16,}['"]'''
tags = ["key", "API", "generic"]
severity = "HIGH"

[[rules]]
id = "jwt-token"
description = "JWT Token"
regex = '''eyJ[A-Za-z0-9-_=]+\.[A-Za-z0-9-_=]+\.?[A-Za-z0-9-_.+/=]*'''
tags = ["key", "JWT"]
severity = "HIGH"

[[rules]]
id = "password"
description = "Password in code"
regex = '''(?i)(password|passwd|pwd)[ ]*[:=][ ]*['"][^'"]{4,}['"]'''
tags = ["key", "password"]
severity = "HIGH"

[[rules]]
id = "mongodb-uri"
description = "MongoDB Connection String"
regex = '''mongodb(\+srv)?:\/\/[^:]+:[^@]+@[^:]+:[0-9]+\/[^"'\s]+'''
tags = ["key", "MongoDB", "database"]
severity = "HIGH"

[[rules]]
id = "aws-access-key"
description = "AWS Access Key"
regex = '''(A3T[A-Z0-9]|AKIA|AGPA|AIDA|AROA|AIPA|ANPA|ANVA|ASIA)[A-Z0-9]{16}'''
tags = ["key", "AWS"]
severity = "HIGH"

[[rules]]
id = "aws-secret-key"
description = "AWS Secret Key"
regex = '''(?i)aws(.{0,20})?(?-i)['\"][0-9a-zA-Z\/+]{40}['\"]'''
tags = ["key", "AWS"]
severity = "HIGH"

[[rules]]
id = "sentry-dsn"
description = "Sentry DSN"
regex = '''https://[a-zA-Z0-9]+@[a-zA-Z0-9]+\.ingest\.sentry\.io/[0-9]+'''
tags = ["key", "Sentry"]
severity = "MEDIUM"

[[rules]]
id = "private-key"
description = "Private Key"
regex = '''-----BEGIN ((RSA|DSA|EC|PGP|OPENSSH) )?PRIVATE KEY( BLOCK)?-----'''
tags = ["key", "private"]
severity = "CRITICAL"

[allowlist]
description = "Allowlisted files"
paths = [
    '''(.*?)(jpg|jpeg|png|gif|svg|webp)$''',
    '''(.*?)(mp3|wav|flac|ogg)$''',
    '''(.*?)(mp4|avi|mov|wmv)$''',
    '''(.*?)(pdf|doc|docx|xls|xlsx|ppt|pptx)$''',
    '''(.*?)(zip|tar|gz|rar)$''',
    '''(.*?)\.min\.(js|css)$''',
    '''(.*?)\.test\.(js|ts)$''',
    '''(.*?)\.spec\.(js|ts)$''',
    '''(.*?)\.example$''',
    '''(.*?)\.sample$''',
    '''(.*?)\.md$''',
    '''(.*?)\.lock$''',
    '''package-lock\.json$''',
    '''yarn\.lock$''',
    '''bun\.lockb$''',
]
