/**
 * Property Favourites Module Exports
 *
 * This module provides comprehensive property favourites management functionality
 * including types, services, queries, and state management.
 */

// Export all types
export type {
	Favourite,
	AddFavouriteInput,
	RemoveFavouriteInput,
	FavouriteQueryParams,
	FavouriteFilters,
	FavouriteStats,
	FavouriteListItem,
	BulkFavouriteOperation,
	FavouriteComparison,
	Pagination,
	ApiResponse,
	FavouriteResponse,
	FavouriteListResponse,
	FavouriteStatsResponse,
	FavouriteComparisonResponse,
	FavouriteStatusResponse,
	FavouriteNotificationSettings,
	WatchListItem,
	CreateWatchListInput,
	RecentlyViewed,
	PropertyRecommendation,
	FavouriteExportOptions,
	FavouriteShareOptions,
	SavedSearch,
	PropertyAlert,
} from "./favourite.type";

// Export all service functions
export {
	addFavourite,
	removeFavourite,
	toggleFavourite,
	getFavourites,
	getFavourite,
	checkFavouriteStatus,
	getFavouriteStats,
	bulkFavouriteOperation,
	exportFavourites,
	shareFavourites,
	compareFavourites,
	clearAllFavourites,
	getPropertyRecommendations,
	addToRecentlyViewed,
	getRecentlyViewed,
	clearRecentlyViewed,
	removeFromRecentlyViewed,
	getWatchLists,
	createWatchList,
	updateWatchList,
	deleteWatchList,
	toggleWatchListStatus,
	getWatchListMatches,
	getSavedSearches,
	createSavedSearch,
	updateSavedSearch,
	deleteSavedSearch,
	runSavedSearch,
	getPropertyAlerts,
	markAlertAsRead,
	markAllAlertsAsRead,
	deleteAlert,
	getNotificationSettings,
	updateNotificationSettings,
	getSimilarToFavourites,
	getPropertiesByTaste,
	createPropertyList,
	getPropertyLists,
	addPropertyToList,
	removePropertyFromList,
	sharePropertyList,
	getFavouriteTrends,
	getMarketInsights,
	getPriceAlerts,
	setPriceAlert,
	removePriceAlert,
} from "./favourite.service";

// Export all query hooks
export {
	favouriteKeys,
	useFavourites,
	useFavourite,
	useFavouriteStatus,
	useFavouriteStats,
	usePropertyRecommendations,
	useRecentlyViewed,
	useWatchLists,
	useWatchListMatches,
	useSavedSearches,
	usePropertyAlerts,
	useNotificationSettings,
	useSimilarToFavourites,
	usePropertiesByTaste,
	usePropertyLists,
	useFavouriteTrends,
	useMarketInsights,
	usePriceAlerts,
	useAddFavourite,
	useRemoveFavourite,
	useToggleFavourite,
	useBulkFavouriteOperation,
	useClearAllFavourites,
	useExportFavourites,
	useShareFavourites,
	useCompareFavourites,
	useAddToRecentlyViewed,
	useClearRecentlyViewed,
	useRemoveFromRecentlyViewed,
	useCreateWatchList,
	useUpdateWatchList,
	useDeleteWatchList,
	useToggleWatchListStatus,
	useCreateSavedSearch,
	useUpdateSavedSearch,
	useDeleteSavedSearch,
	useRunSavedSearch,
	useMarkAlertAsRead,
	useMarkAllAlertsAsRead,
	useDeleteAlert,
	useUpdateNotificationSettings,
	useCreatePropertyList,
	useAddPropertyToList,
	useRemovePropertyFromList,
	useSharePropertyList,
	useSetPriceAlert,
	useRemovePriceAlert,
	usePrefetchFavourite,
	useInvalidateFavourites,
	useOptimisticFavouriteToggle,
} from "./favourite.queries";

// Export store and selectors
export {
	useFavouriteStore,
	useFavouriteModals,
	useFavouriteModal,
	useSelectedFavourites,
	useSelectedProperties,
	useHasSelectedFavourites,
	useSelectedFavouritesCount,
	useFavouriteForm,
	useCurrentFavourite,
	useFavouriteFilters,
	useFavouriteQueryParams,
	// useActiveFiltersCount,
	useFavouriteViewPreferences,
	useFavouriteViewMode,
	useCompareMode,
	useCompareList,
	useUnreadAlertsCount,
	useShowNotificationBadge,
	useFavouriteLoading,
	// useBulkActionLoading,
} from "./favourite.store";
