/**
 * Property Conditions Module Exports
 *
 * This module provides comprehensive property condition management functionality
 * including types, services, queries, and state management.
 */

// Export all query hooks
export {
  conditionKeys,
  useAddConditionItem,
  useBulkUpdateConditionReports,
  useCompareConditionReports,
  useCompleteConditionReport,
  useConditionInsights,
  useConditionMetrics,
  useConditionNotificationSettings,
  useConditionReport,
  useConditionReports,
  useConditionReportsByProperty,
  useConditionReportsByTenant,
  useConditionStats,
  useConditionTemplates,
  useCreateConditionReport,
  useCreateConditionTemplate,
  useDeleteConditionReport,
  useDisputeConditionReport,
  useExportConditionReports,
  useInvalidateConditions,
  usePrefetchConditionReport,
  usePropertyConditionHistory,
  usePropertyConditionSummary,
  usePropertyConditionTrends,
  useSignConditionReport,
  useUpdateConditionItem,
  useUpdateConditionNotificationSettings,
  useUpdateConditionReport,
  useUpdateConditionTemplate,
  useUploadConditionPhotos,
} from "./condition.queries";
// Export all service functions
export {
  addConditionItem,
  archiveConditionReport,
  bulkUpdateConditionReports,
  compareConditionReports,
  completeConditionReport,
  createConditionReport,
  createConditionTemplate,
  createReportFromTemplate,
  deleteConditionItem,
  deleteConditionPhoto,
  deleteConditionReport,
  deleteConditionTemplate,
  deleteReportAttachment,
  disputeConditionReport,
  duplicateConditionReport,
  exportConditionReports,
  generateConditionReportPDF,
  getConditionAuditLogs,
  getConditionInsights,
  getConditionMetrics,
  getConditionNotificationSettings,
  getConditionReport,
  getConditionReports,
  getConditionReportsByProperty,
  getConditionReportsByTenant,
  getConditionStats,
  getConditionTemplates,
  getPropertyConditionHistory,
  getPropertyConditionSummary,
  getPropertyConditionTrends,
  resolveDispute,
  schedulePeriodicConditionCheck,
  sendConditionReportNotification,
  sendSignatureRequest,
  signConditionReport,
  updateConditionItem,
  updateConditionNotificationSettings,
  updateConditionReport,
  updateConditionTemplate,
  uploadConditionPhotos,
  uploadReportAttachment,
  validateConditionData,
} from "./condition.service";
// Export store and selectors
export {
  useActiveConditionFiltersCount,
  useActiveConditionProperty,
  useConditionBulkActionLoading,
  useConditionCompareList,
  useConditionFilters,
  useConditionForm,
  useConditionLoading,
  useConditionModal,
  useConditionModals,
  useConditionQueryParams,
  useConditionStore,
  useConditionViewMode,
  useConditionViewPreferences,
  useCurrentCondition,
  useHasSelectedConditions,
  useSelectedConditions,
  useSelectedConditionsCount,
} from "./condition.store";
// Export all types
export type {
  AddConditionItemInput,
  ApiResponse,
  BulkConditionOperation,
  ConditionAuditLog,
  ConditionComparison,
  ConditionComparisonResponse,
  ConditionExportOptions,
  ConditionFilters,
  ConditionItem,
  ConditionItemTrend,
  ConditionListResponse,
  ConditionNotificationSettings,
  ConditionPhoto,
  ConditionQueryParams,
  ConditionResponse,
  ConditionSignature,
  ConditionStats,
  ConditionStatsResponse,
  ConditionTemplate,
  ConditionTemplatesResponse,
  CreateConditionReportInput,
  DisputeConditionReportInput,
  Pagination,
  PropertyCondition,
  PropertyConditionSummary,
  SignConditionReportInput,
  UpdateConditionItemInput,
  UpdateConditionReportInput,
} from "./condition.type";
// Export enums
export {
  ConditionCategory,
  ConditionStatus,
  ReportType,
} from "./condition.type";
