apiVersion: 1

contactPoints:
  - name: email-notifications
    receivers:
      - uid: email-notification
        type: email
        settings:
          addresses: alerts@kenyarentals.com
          singleEmail: false

  - name: slack-notifications
    receivers:
      - uid: slack-notification
        type: slack
        settings:
          url: ${SLACK_WEBHOOK_URL}
          title: "{{ .Status | title }} - {{ .CommonLabels.alertname }}"
          text: >-
            {{ range .Alerts }}
              *Alert:* {{ .Labels.alertname }}
              *Description:* {{ .Annotations.description }}
              *Severity:* {{ .Labels.severity }}
              *Value:* {{ .ValueString }}
              {{ if .Labels.instance }}*Instance:* {{ .Labels.instance }}{{ end }}
              {{ if .Labels.service }}*Service:* {{ .Labels.service }}{{ end }}
            {{ end }}

  - name: pagerduty-critical
    receivers:
      - uid: pagerduty-critical
        type: pagerduty
        settings:
          integrationKey: ${PAGERDUTY_INTEGRATION_KEY}
          severity: critical
          class: production
          component: api
          group: kenya-rentals
          summary: "{{ .CommonLabels.alertname }}"
          customDetails: "{{ range .Alerts }}{{ .Annotations.description }}{{ end }}"
