apiVersion: 1

policies:
  - name: Kenya Rentals API Alerts
    receiver: slack-notifications
    group_by: ['alertname', 'service']
    repeat_interval: 4h
    routes:
      - receiver: email-notifications
        matchers:
          - severity =~ "warning|info"
        group_wait: 30s
        group_interval: 5m
        repeat_interval: 4h
        mute_time_intervals: []
        
      - receiver: pagerduty-critical
        matchers:
          - severity = "critical"
        group_wait: 30s
        group_interval: 5m
        repeat_interval: 1h
        mute_time_intervals: []
