/**
 * Work Orders Module Exports
 *
 * This module provides comprehensive work order management functionality
 * including types, services, queries, and state management for property
 * maintenance and repair operations.
 */

// Export all query hooks
export {
  useAddMaterial,
  useAddTimeEntry,
  useAddWorkOrderUpdate,
  useAssignWorkOrder,
  useBulkUpdateWorkOrders,
  useCancelWorkOrder,
  useCompleteWorkOrder,
  useCreateRecurringWorkOrder,
  useCreateWorkOrder,
  useCreateWorkOrderTemplate,
  useDeleteMaterial,
  useDeleteRecurringWorkOrder,
  useDeleteTimeEntry,
  useDeleteWorkOrder,
  useDeleteWorkOrderAttachment,
  useDeleteWorkOrderTemplate,
  useDuplicateWorkOrder,
  useExportWorkOrders,
  useGenerateNextWorkOrder,
  useGenerateWorkOrderReport,
  useInvalidateWorkOrders,
  useOverdueWorkOrders,
  usePrefetchWorkOrder,
  useRecurringWorkOrders,
  useSendWorkOrderNotification,
  useSendWorkOrderReminder,
  useUpcomingWorkOrders,
  useUpdateMaterial,
  useUpdateQualityCheck,
  useUpdateRecurringWorkOrder,
  useUpdateTimeEntry,
  useUpdateWorkOrder,
  useUpdateWorkOrderTemplate,
  useUploadWorkOrderAttachment,
  useValidateWorkOrderConflicts,
  useWorkOrder,
  useWorkOrderCalendarEvents,
  // useContractorAvailability,
  // useAvailableContractors,
  useWorkOrderCostBreakdown,
  useWorkOrderHistory,
  useWorkOrderStats,
  useWorkOrders,
  useWorkOrdersByContractor,
  useWorkOrdersByProperty,
  useWorkOrderTemplates,
  workOrderKeys,
} from "./work-order.queries";
// Export all service functions
export {
  addMaterial,
  addTimeEntry,
  addWorkOrderUpdate,
  assignWorkOrder,
  bulkUpdateWorkOrders,
  calculateWorkOrderCosts,
  cancelWorkOrder,
  completeWorkOrder,
  createRecurringWorkOrder,
  createWorkOrder,
  createWorkOrderTemplate,
  deleteMaterial,
  deleteRecurringWorkOrder,
  deleteTimeEntry,
  deleteWorkOrder,
  deleteWorkOrderAttachment,
  deleteWorkOrderTemplate,
  downloadWorkOrderReport,
  duplicateWorkOrder,
  exportWorkOrders,
  generateNextWorkOrder,
  generateWorkOrderReport,
  getAvailableContractors,
  getContractorAvailability,
  getOverdueWorkOrders,
  getRecurringWorkOrders,
  getUpcomingWorkOrders,
  getWorkOrder,
  getWorkOrderCalendarEvents,
  getWorkOrderCostBreakdown,
  getWorkOrderHistory,
  getWorkOrderStats,
  getWorkOrders,
  getWorkOrdersByContractor,
  getWorkOrdersByProperty,
  getWorkOrderTemplates,
  sendWorkOrderNotification,
  sendWorkOrderReminder,
  updateMaterial,
  updateQualityCheck,
  updateRecurringWorkOrder,
  updateTimeEntry,
  updateWorkOrder,
  updateWorkOrderTemplate,
  uploadWorkOrderAttachment,
  validateWorkOrderConflicts,
} from "./work-order.service";
// Export store and selectors
export {
  useActiveContractor,
  useActiveFiltersCount,
  useActiveProperty,
  useBulkActionLoading,
  useCurrentWorkOrder,
  useHasSelectedWorkOrders,
  useSelectedWorkOrders,
  useSelectedWorkOrdersCount,
  useWorkOrderFilters,
  useWorkOrderForm,
  useWorkOrderLoading,
  useWorkOrderModal,
  useWorkOrderModals,
  useWorkOrderQueryParams,
  useWorkOrderStore,
  useWorkOrderViewMode,
  useWorkOrderViewPreferences,
} from "./work-order.store";
// Export all types
export type {
  AddMaterialInput,
  AddTimeEntryInput,
  AddUpdateInput,
  ApiResponse,
  AssignWorkOrderInput,
  BulkWorkOrderOperation,
  CompleteWorkOrderInput,
  ContractorAvailability,
  CreateWorkOrderInput,
  Pagination,
  QualityCheck,
  RecurrencePattern,
  RecurringWorkOrder,
  RecurringWorkOrdersResponse,
  UpdateWorkOrderInput,
  WorkOrder,
  WorkOrderAttachment,
  WorkOrderCalendarEvent,
  WorkOrderCostBreakdown,
  WorkOrderCostBreakdownResponse,
  WorkOrderExportOptions,
  WorkOrderFilters,
  WorkOrderListResponse,
  WorkOrderMaterial,
  WorkOrderNotificationSettings,
  WorkOrderQueryParams,
  WorkOrderReport,
  WorkOrderResponse,
  WorkOrderStats,
  WorkOrderStatsResponse,
  WorkOrderTemplate,
  WorkOrderTemplatesResponse,
  WorkOrderTimeEntry,
  WorkOrderUpdate,
} from "./work-order.type";
// Export enums
export {
  WorkOrderPriority,
  WorkOrderStatus,
  WorkOrderType,
} from "./work-order.type";
