// M-Pesa error codes and messages
export const MPESA_ERROR_CODES = {
  "0": "Success",
  "1": "Insufficient funds",
  "2": "Less than minimum transaction value",
  "3": "More than maximum transaction value",
  "4": "Would exceed daily transfer limit",
  "5": "Would exceed minimum balance",
  "6": "Unresolved primary party",
  "7": "Unresolved receiver party",
  "8": "Would exceed maximum balance",
  "11": "Debit account invalid",
  "12": "Credit account invalid",
  "13": "Unresolved debit account",
  "14": "Unresolved credit account",
  "15": "Duplicate detected",
  "17": "Internal failure",
  "20": "Unresolved initiator",
  "26": "Traffic blocking condition in place",
  "1001": "Request could not be processed",
  "1002": "Request received but could not be processed",
  "1003": "Request received but could not be processed",
  "1004": "Request received but could not be processed",
  "1005": "Request received but could not be processed",
  "1006": "Request received but could not be processed",
  "1007": "Request received but could not be processed",
  "1008": "Request received but could not be processed",
  "1009": "Request received but could not be processed",
  "1010": "Request received but could not be processed",
  "1011": "Request received but could not be processed",
  "1012": "Request received but could not be processed",
  "1013": "Request received but could not be processed",
  "1014": "Request received but could not be processed",
  "1015": "Request received but could not be processed",
  "1016": "Request received but could not be processed",
  "1017": "Request received but could not be processed",
  "1018": "Request received but could not be processed",
  "1019": "Request received but could not be processed",
  "1020": "Request received but could not be processed",
  "1021": "Request received but could not be processed",
  "1022": "Request received but could not be processed",
  "1023": "Request received but could not be processed",
  "1024": "Request received but could not be processed",
  "1025": "Request received but could not be processed",
  "1026": "Request received but could not be processed",
  "1027": "Request received but could not be processed",
  "1028": "Request received but could not be processed",
  "1029": "Request received but could not be processed",
  "1030": "Request received but could not be processed",
  "1031": "Request received but could not be processed",
  "1032": "Request received but could not be processed",
  "1033": "Request received but could not be processed",
  "1034": "Request received but could not be processed",
  "1035": "Request received but could not be processed",
  "1036": "Request received but could not be processed",
  "1037": "Request received but could not be processed",
  "1038": "Request received but could not be processed",
  "1039": "Request received but could not be processed",
  "1040": "Request received but could not be processed",
  "1041": "Request received but could not be processed",
  "1042": "Request received but could not be processed",
  "1043": "Request received but could not be processed",
  "1044": "Request received but could not be processed",
  "1045": "Request received but could not be processed",
  "1046": "Request received but could not be processed",
  "1047": "Request received but could not be processed",
  "1048": "Request received but could not be processed",
  "1049": "Request received but could not be processed",
  "1050": "Request received but could not be processed",
  "1051": "Request received but could not be processed",
  "1052": "Request received but could not be processed",
  "1053": "Request received but could not be processed",
  "1054": "Request received but could not be processed",
  "1055": "Request received but could not be processed",
  "1056": "Request received but could not be processed",
  "1057": "Request received but could not be processed",
  "1058": "Request received but could not be processed",
  "1059": "Request received but could not be processed",
  "1060": "Request received but could not be processed",
  "1061": "Request received but could not be processed",
  "1062": "Request received but could not be processed",
  "1063": "Request received but could not be processed",
  "1064": "Request received but could not be processed",
  "1065": "Request received but could not be processed",
  "1066": "Request received but could not be processed",
  "1067": "Request received but could not be processed",
  "1068": "Request received but could not be processed",
  "1069": "Request received but could not be processed",
  "1070": "Request received but could not be processed",
  "1071": "Request received but could not be processed",
  "1072": "Request received but could not be processed",
  "1073": "Request received but could not be processed",
  "1074": "Request received but could not be processed",
  "1075": "Request received but could not be processed",
  "1076": "Request received but could not be processed",
  "1077": "Request received but could not be processed",
  "1078": "Request received but could not be processed",
  "1079": "Request received but could not be processed",
  "1080": "Request received but could not be processed",
  "1081": "Request received but could not be processed",
  "1082": "Request received but could not be processed",
  "1083": "Request received but could not be processed",
  "1084": "Request received but could not be processed",
  "1085": "Request received but could not be processed",
  "1086": "Request received but could not be processed",
  "1087": "Request received but could not be processed",
  "1088": "Request received but could not be processed",
  "1089": "Request received but could not be processed",
  "1090": "Request received but could not be processed",
  "1091": "Request received but could not be processed",
  "1092": "Request received but could not be processed",
  "1093": "Request received but could not be processed",
  "1094": "Request received but could not be processed",
  "1095": "Request received but could not be processed",
  "1096": "Request received but could not be processed",
  "1097": "Request received but could not be processed",
  "1098": "Request received but could not be processed",
  "1099": "Request received but could not be processed",
  "1200": "Request received but could not be processed",
  "1201": "Request received but could not be processed",
  "1202": "Request received but could not be processed",
  "1203": "Request received but could not be processed",
  "1204": "Request received but could not be processed",
  "1205": "Request received but could not be processed",
  "1206": "Request received but could not be processed",
  "1207": "Request received but could not be processed",
  "1208": "Request received but could not be processed",
  "1209": "Request received but could not be processed",
  "1210": "Request received but could not be processed",
  "1211": "Request received but could not be processed",
  "1212": "Request received but could not be processed",
  "1213": "Request received but could not be processed",
  "1214": "Request received but could not be processed",
  "1215": "Request received but could not be processed",
  "1216": "Request received but could not be processed",
  "1217": "Request received but could not be processed",
  "1218": "Request received but could not be processed",
  "1219": "Request received but could not be processed",
  "1220": "Request received but could not be processed",
  "1221": "Request received but could not be processed",
  "1222": "Request received but could not be processed",
  "1223": "Request received but could not be processed",
  "1224": "Request received but could not be processed",
  "1225": "Request received but could not be processed",
  "1226": "Request received but could not be processed",
  "1227": "Request received but could not be processed",
  "1228": "Request received but could not be processed",
  "1229": "Request received but could not be processed",
  "1230": "Request received but could not be processed",
  "1231": "Request received but could not be processed",
  "1232": "Request received but could not be processed",
  "1233": "Request received but could not be processed",
  "1234": "Request received but could not be processed",
  "1235": "Request received but could not be processed",
  "1236": "Request received but could not be processed",
  "1237": "Request received but could not be processed",
  "1238": "Request received but could not be processed",
  "1239": "Request received but could not be processed",
  "1240": "Request received but could not be processed",
  "1241": "Request received but could not be processed",
};
